### PR TITLE
New Theme proposal

### PR DESCRIPTION
**Pull request by xakraz**
Refers to #2 but for Netlify integration testing

### CODE REVIEW

**Comment by xakraz** [comment]
Preview: https://5ed8c1a7c1eb170007f318fd--p7t.netlify.app/

**Comment by xakraz** [comment]
Even nice mobile responsive :stuck_out_tongue: 

## Normal view

Screenshot_20200604-135000_Chrome


## Full page view

Screenshot_20200604-134909_Chrome

**Comment by guilhem** [comment]
In a way to change name from p7t to DevObs, may ou change the order?

1. DevObs
2. DTK
3. LetsDeploy
4. VPNI

What about actu to its page?

**Comment by xakraz** [comment]
The LoveIt theme use the "blog" feature of Hugo.
The order is automatically applied according to the date of the post.

We can fake the date to force the order.
Later if we want to make DevObs the main brand, we can add a specific "about" page explaining all that and let the blog post structure work as expected wdyt ?

About `Actu`, I think it has its own place here. why not ?
You talk about them in #podcast on Discord :smile:

**Comment by xakraz** [comment]
So @guilhem What do we do regarding this PR ?

**Review by Mustafaa0 — APPROVED** [review]

**Pull request closed without merging**
